# fly.toml app configuration file generated for tech-task-ip-lookup on 2025-01-25T14:06:41+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tech-task-ip-lookup'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/v1/health"

[[vm]]
  size = 'shared-cpu-1x'
